from setuptools import setup

setup(
    name='blockchain_message',
    version='',
    packages=['test', 'venv.lib.python3.6.site-packages.ens', 'venv.lib.python3.6.site-packages.pip',
              'venv.lib.python3.6.site-packages.pip._vendor', 'venv.lib.python3.6.site-packages.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip._internal', 'venv.lib.python3.6.site-packages.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip._internal.operations', 'venv.lib.python3.6.site-packages.rlp',
              'venv.lib.python3.6.site-packages.rlp.sedes', 'venv.lib.python3.6.site-packages.rsa',
              'venv.lib.python3.6.site-packages.tlz', 'venv.lib.python3.6.site-packages.idna',
              'venv.lib.python3.6.site-packages.pytz', 'venv.lib.python3.6.site-packages.solc',
              'venv.lib.python3.6.site-packages.solc.utils', 'venv.lib.python3.6.site-packages.web3',
              'venv.lib.python3.6.site-packages.web3.auto', 'venv.lib.python3.6.site-packages.web3.utils',
              'venv.lib.python3.6.site-packages.web3.utils.six', 'venv.lib.python3.6.site-packages.web3.utils.toolz',
              'venv.lib.python3.6.site-packages.web3.utils.module_testing',
              'venv.lib.python3.6.site-packages.web3.providers',
              'venv.lib.python3.6.site-packages.web3.providers.eth_tester',
              'venv.lib.python3.6.site-packages.web3.middleware',
              'venv.lib.python3.6.site-packages.web3.gas_strategies', 'venv.lib.python3.6.site-packages.babel',
              'venv.lib.python3.6.site-packages.babel.messages', 'venv.lib.python3.6.site-packages.babel.localtime',
              'venv.lib.python3.6.site-packages.toolz', 'venv.lib.python3.6.site-packages.toolz.curried',
              'venv.lib.python3.6.site-packages.toolz.sandbox', 'venv.lib.python3.6.site-packages.Crypto',
              'venv.lib.python3.6.site-packages.Crypto.IO', 'venv.lib.python3.6.site-packages.Crypto.Hash',
              'venv.lib.python3.6.site-packages.Crypto.Math', 'venv.lib.python3.6.site-packages.Crypto.Util',
              'venv.lib.python3.6.site-packages.Crypto.Cipher', 'venv.lib.python3.6.site-packages.Crypto.Random',
              'venv.lib.python3.6.site-packages.Crypto.Protocol', 'venv.lib.python3.6.site-packages.Crypto.SelfTest',
              'venv.lib.python3.6.site-packages.Crypto.SelfTest.IO',
              'venv.lib.python3.6.site-packages.Crypto.SelfTest.Hash',
              'venv.lib.python3.6.site-packages.Crypto.SelfTest.Math',
              'venv.lib.python3.6.site-packages.Crypto.SelfTest.Util',
              'venv.lib.python3.6.site-packages.Crypto.SelfTest.Cipher',
              'venv.lib.python3.6.site-packages.Crypto.SelfTest.Random',
              'venv.lib.python3.6.site-packages.Crypto.SelfTest.Protocol',
              'venv.lib.python3.6.site-packages.Crypto.SelfTest.PublicKey',
              'venv.lib.python3.6.site-packages.Crypto.SelfTest.Signature',
              'venv.lib.python3.6.site-packages.Crypto.PublicKey', 'venv.lib.python3.6.site-packages.Crypto.Signature',
              'venv.lib.python3.6.site-packages.jinja2', 'venv.lib.python3.6.site-packages.pyasn1',
              'venv.lib.python3.6.site-packages.pyasn1.type', 'venv.lib.python3.6.site-packages.pyasn1.codec',
              'venv.lib.python3.6.site-packages.pyasn1.codec.ber', 'venv.lib.python3.6.site-packages.pyasn1.codec.cer',
              'venv.lib.python3.6.site-packages.pyasn1.codec.der',
              'venv.lib.python3.6.site-packages.pyasn1.codec.native', 'venv.lib.python3.6.site-packages.pyasn1.compat',
              'venv.lib.python3.6.site-packages.sphinx', 'venv.lib.python3.6.site-packages.sphinx.cmd',
              'venv.lib.python3.6.site-packages.sphinx.ext', 'venv.lib.python3.6.site-packages.sphinx.ext.autodoc',
              'venv.lib.python3.6.site-packages.sphinx.ext.napoleon',
              'venv.lib.python3.6.site-packages.sphinx.ext.autosummary', 'venv.lib.python3.6.site-packages.sphinx.util',
              'venv.lib.python3.6.site-packages.sphinx.util.stemmer', 'venv.lib.python3.6.site-packages.sphinx.locale',
              'venv.lib.python3.6.site-packages.sphinx.pycode', 'venv.lib.python3.6.site-packages.sphinx.search',
              'venv.lib.python3.6.site-packages.sphinx.domains', 'venv.lib.python3.6.site-packages.sphinx.testing',
              'venv.lib.python3.6.site-packages.sphinx.writers', 'venv.lib.python3.6.site-packages.sphinx.builders',
              'venv.lib.python3.6.site-packages.sphinx.builders.latex',
              'venv.lib.python3.6.site-packages.sphinx.directives',
              'venv.lib.python3.6.site-packages.sphinx.transforms',
              'venv.lib.python3.6.site-packages.sphinx.transforms.post_transforms',
              'venv.lib.python3.6.site-packages.sphinx.websupport',
              'venv.lib.python3.6.site-packages.sphinx.websupport.search',
              'venv.lib.python3.6.site-packages.sphinx.websupport.storage',
              'venv.lib.python3.6.site-packages.sphinx.environment',
              'venv.lib.python3.6.site-packages.sphinx.environment.adapters',
              'venv.lib.python3.6.site-packages.sphinx.environment.collectors',
              'venv.lib.python3.6.site-packages.certifi', 'venv.lib.python3.6.site-packages.chardet',
              'venv.lib.python3.6.site-packages.chardet.cli', 'venv.lib.python3.6.site-packages.cytoolz',
              'venv.lib.python3.6.site-packages.cytoolz.curried', 'venv.lib.python3.6.site-packages.eth_abi',
              'venv.lib.python3.6.site-packages.eth_abi.utils', 'venv.lib.python3.6.site-packages.eth_rlp',
              'venv.lib.python3.6.site-packages.ipfsapi', 'venv.lib.python3.6.site-packages.urllib3',
              'venv.lib.python3.6.site-packages.urllib3.util', 'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.attrdict', 'venv.lib.python3.6.site-packages.docutils',
              'venv.lib.python3.6.site-packages.docutils.utils', 'venv.lib.python3.6.site-packages.docutils.utils.math',
              'venv.lib.python3.6.site-packages.docutils.parsers',
              'venv.lib.python3.6.site-packages.docutils.parsers.rst',
              'venv.lib.python3.6.site-packages.docutils.parsers.rst.languages',
              'venv.lib.python3.6.site-packages.docutils.parsers.rst.directives',
              'venv.lib.python3.6.site-packages.docutils.readers', 'venv.lib.python3.6.site-packages.docutils.writers',
              'venv.lib.python3.6.site-packages.docutils.writers.xetex',
              'venv.lib.python3.6.site-packages.docutils.writers.latex2e',
              'venv.lib.python3.6.site-packages.docutils.writers.odf_odt',
              'venv.lib.python3.6.site-packages.docutils.writers.s5_html',
              'venv.lib.python3.6.site-packages.docutils.writers.pep_html',
              'venv.lib.python3.6.site-packages.docutils.writers.html4css1',
              'venv.lib.python3.6.site-packages.docutils.writers.html5_polyglot',
              'venv.lib.python3.6.site-packages.docutils.languages',
              'venv.lib.python3.6.site-packages.docutils.transforms', 'venv.lib.python3.6.site-packages.eth_hash',
              'venv.lib.python3.6.site-packages.eth_hash.backends', 'venv.lib.python3.6.site-packages.eth_keys',
              'venv.lib.python3.6.site-packages.eth_keys.utils', 'venv.lib.python3.6.site-packages.eth_keys.backends',
              'venv.lib.python3.6.site-packages.eth_keys.backends.native', 'venv.lib.python3.6.site-packages.hexbytes',
              'venv.lib.python3.6.site-packages.pygments', 'venv.lib.python3.6.site-packages.pygments.lexers',
              'venv.lib.python3.6.site-packages.pygments.styles', 'venv.lib.python3.6.site-packages.pygments.filters',
              'venv.lib.python3.6.site-packages.pygments.formatters', 'venv.lib.python3.6.site-packages.requests',
              'venv.lib.python3.6.site-packages.alabaster', 'venv.lib.python3.6.site-packages.eth_utils',
              'venv.lib.python3.6.site-packages.eth_utils.typing', 'venv.lib.python3.6.site-packages.eth_utils.curried',
              'venv.lib.python3.6.site-packages.packaging', 'venv.lib.python3.6.site-packages.eth_typing',
              'venv.lib.python3.6.site-packages.markupsafe', 'venv.lib.python3.6.site-packages.websockets',
              'venv.lib.python3.6.site-packages.websockets.py35', 'venv.lib.python3.6.site-packages.websockets.py36',
              'venv.lib.python3.6.site-packages.websockets.extensions', 'venv.lib.python3.6.site-packages.eth_account',
              'venv.lib.python3.6.site-packages.eth_account.signers',
              'venv.lib.python3.6.site-packages.eth_account.internal', 'venv.lib.python3.6.site-packages.eth_keyfile',
              'venv.lib.python3.6.site-packages.parsimonious', 'venv.lib.python3.6.site-packages.parsimonious.tests',
              'venv.lib.python3.6.site-packages.sphinxcontrib.websupport',
              'venv.lib.python3.6.site-packages.sphinxcontrib.websupport.search',
              'venv.lib.python3.6.site-packages.sphinxcontrib.websupport.storage',
              'venv.lib.python3.6.site-packages.snowballstemmer', 'venv.lib.python3.6.site-packages.semantic_version',
              'client', 'blockchain_message', 'blockchain_message.src'],
    url='',
    license='GPL',
    author='Sean Batzel',
    author_email='romulus108@protonmail.com',
    description='', install_requires=['rsa']
)
