make:
	pdflatex blockchain_message
	makeindex blockchain_message
	makeglossaries blockchain_message
	biber blockchain_message
	biber blockchain_message
	pdflatex blockchain_message
	pdflatex blockchain_message

clean:
	rm -f blockchain_message.aux
	rm -f blockchain_message.glo
	rm -f blockchain_message.idx
	rm -f blockchain_message.log
	rm -f blockchain_message.pdf
	rm -f blockchain_message.synctex.gz
	rm -f blockchain_message.toc
	rm -f blockchain_message.ist
	rm -f blockchain_message.glg
	rm -f blockchain_message.gls
	rm -f blockchain_message.ilg
	rm -f blockchain_message.ind
	rm -f blockchain_message.run.xml
	rm -f blockchain_message.bcf
	rm -f blockchain_message.bbl
	rm -f blockchain_message.blg
	rm -f blockchain_message.out
	rm -f texput.log
	rm -f blockchain_message.lof
	rm -f blockchain_message.lot
